#!/usr/bin/env bash
# TEMP_AUTH_DISABLED: Script de teste rápido para verificar status do modo dev

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🔍 VERIFICADOR: Modo Desenvolvimento sem Autenticação        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "ℹ️  Instruções de teste manual:"
echo ""
echo "1️⃣  VERIFICAR FLAG EM App.tsx:"
echo "   Abra: src/App.tsx"
echo "   Procure por: const TEMP_AUTH_DISABLED = true"
echo "   ✅ Se vir 'true': modo dev ATIVADO"
echo "   ❌ Se vir 'false': modo dev DESATIVADO (auth original ativa)"
echo ""
echo "2️⃣  INICIAR SERVIDOR:"
echo "   $ npm run dev"
echo "   Acesse: http://localhost:5173"
echo ""
echo "3️⃣  VERIFICAÇÕES NO BROWSER:"
echo "   ✅ Pula tela de login?"
echo "   ✅ Vai direto para /dashboard?"
echo "   ✅ Sidebar mostra 'Dev User (Mock)' com avatar 'D('?"
echo "   ✅ Console (F12) mostra '⚠️ TEMP_AUTH_DISABLED'?"
echo "   ✅ Consegue clicar em links do sidebar?"
echo ""
echo "4️⃣  CONSOLE DO NAVEGADOR (F12):"
echo "   Copie e cole:"
echo ""
echo "   localStorage.getItem('TEMP_AUTH_DISABLED_MODE')"
echo "   // Retorna: 'true' ✅"
echo ""
echo "   localStorage.getItem('user_profile')"
echo "   // Retorna: JSON com { email: 'dev@localhost.test', ... }"
echo ""
echo "5️⃣  DESATIVAR MODO DEV (para reativar auth):"
echo "   Em src/App.tsx, mude:"
echo ""
echo "   // DE:"
echo "   const TEMP_AUTH_DISABLED = true;"
echo ""
echo "   // PARA:"
echo "   const TEMP_AUTH_DISABLED = false;"
echo ""
echo "   Salve, recarregue → vai pedir login"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📝 Arquivo de referência: TEMP_AUTH_DISABLED_README.md"
echo "════════════════════════════════════════════════════════════════"
